blueprint:
  name: Universal Critical Values Monitor (hold per entity)
  description: >
    Универсальный мониторинг критических значений с удержанием для каждого сенсора
  domain: automation

  input:
    entities_config:
      name: Entities Configuration
      description: >
        Пример:
        - entity_id: sensor.temp
          name: Температура
          unit: °C
          check_above: 28
          check_below: 18
          hold_seconds: 60
          action: Включить кондиционер
      selector:
        object:

trigger:
  - platform: state

variables:
  entities_config: !input entities_config
  monitored_entities: >
    {{ entities_config | map(attribute='entity_id') | list }}

condition:
  - condition: template
    value_template: "{{ trigger.entity_id in monitored_entities }}"

action:

  - variables:
      entity_id: "{{ trigger.entity_id }}"
      state_now: "{{ states(entity_id) }}"
      entity_config: >
        {% for item in entities_config %}
          {% if item.entity_id == entity_id %}
            {{ item }}
          {% endif %}
        {% endfor %}

      check_result: >
        {% set c = entity_config %}
        {% set value = state_now %}
        {% set num_value = value | float(default=none) %}
        {% set is_numeric = num_value is not none %}
        {% set alert = false %}
        {% set reason = '' %}
        {% set threshold = 0 %}
        {% if is_numeric %}
          {% if c.check_above is defined and num_value > c.check_above %}
            {% set alert = true %}{% set reason = 'above' %}{% set threshold = c.check_above %}
          {% elif c.check_below is defined and num_value < c.check_below %}
            {% set alert = true %}{% set reason = 'below' %}{% set threshold = c.check_below %}
          {% endif %}
        {% else %}
          {% if c.check_state is defined and value == c.check_state %}
            {% set alert = true %}{% set reason = 'state_match' %}
          {% elif c.check_states is defined and value in c.check_states %}
            {% set alert = true %}{% set reason = 'state_in_list' %}
          {% endif %}
        {% endif %}
        {{ {'alert': alert, 'reason': reason, 'threshold': threshold} }}

  # Если значение критическое — ждём указанное для entity время
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ check_result.alert }}"
        sequence:
          - delay:
              seconds: "{{ entity_config.hold_seconds | default(30) }}"

          - variables:
              state_now: "{{ states(entity_id) }}"
              # повторная проверка после задержки
              check_result_after: >
                {% set c = entity_config %}
                {% set value = state_now %}
                {% set num_value = value | float(default=none) %}
                {% set is_numeric = num_value is not none %}
                {% set alert = false %}
                {% set reason = '' %}
                {% set threshold = 0 %}
                {% if is_numeric %}
                  {% if c.check_above is defined and num_value > c.check_above %}
                    {% set alert = true %}{% set reason = 'above' %}{% set threshold = c.check_above %}
                  {% elif c.check_below is defined and num_value < c.check_below %}
                    {% set alert = true %}{% set reason = 'below' %}{% set threshold = c.check_below %}
                  {% endif %}
                {% else %}
                  {% if c.check_state is defined and value == c.check_state %}
                    {% set alert = true %}{% set reason = 'state_match' %}
                  {% elif c.check_states is defined and value in c.check_states %}
                    {% set alert = true %}{% set reason = 'state_in_list' %}
                  {% endif %}
                {% endif %}
                {{ {'alert': alert, 'reason': reason, 'threshold': threshold} }}

          - condition: template
            value_template: "{{ check_result_after.alert }}"

          - choose:

              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason == 'above' }}"
                sequence:
                  - action: notify.send_message
                    target:
                      entity_id: notify.alarm
                    data:
                      message: >
                        🚨 *ПРЕВЫШЕНИЕ - {{ entity_config.name | default(entity_id) }}*
                        📊 {{ state_now }}{{ entity_config.unit | default('') }}
                        📈 Порог: {{ check_result_after.threshold }}{{ entity_config.unit | default('') }}
                        ⚠️ Критический
                        💡 {{ entity_config.action | default('Требуется вмешательство') }}

              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason == 'below' }}"
                sequence:
                  - action: notify.send_message
                    target:
                      entity_id: notify.alarm
                    data:
                      message: >
                        🚨 *НИЖЕ НОРМЫ - {{ entity_config.name | default(entity_id) }}*
                        📊 {{ state_now }}{{ entity_config.unit | default('') }}
                        📉 Порог: {{ check_result_after.threshold }}{{ entity_config.unit | default('') }}
                        ⚠️ Критический
                        💡 {{ entity_config.action | default('Требуется вмешательство') }}

              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason in ['state_match','state_in_list'] }}"
                sequence:
                  - action: notify.send_message
                    target:
                      entity_id: notify.alarm
                    data:
                      message: >
                        🚨 *КРИТИЧЕСКОЕ СОСТОЯНИЕ - {{ entity_config.name | default(entity_id) }}*
                        📊 {{ state_now }}
                        ⚠️ Требует внимания
                        💡 {{ entity_config.action | default('Требуется проверка') }}

mode: single
