blueprint:
  name: Universal Critical Values Monitor
  description: Универсальный мониторинг критических значений с поддержкой разных типов данных
  domain: automation
  input:
    telegram_chat_id:
      name: Telegram Chat ID
      description: ID чата или имя пользователя в Telegram
      selector:
        text:
    entities_config:
      name: Entities Configuration
      description: Список сущностей для мониторинга в формате YAML
      selector:
        object:

trigger:
  - platform: state
    entity_id: >
      {% set entities = [] %}
      {% for item in inputs.entities_config %}
        {% set _ = entities.append(item.entity_id) %}
      {% endfor %}
      {{ entities }}

variables:
  telegram_chat_id: !input telegram_chat_id
  entities_config: !input entities_config

action:
  - variables:
      entity_id: "{{ trigger.entity_id }}"
      new_state: "{{ trigger.to_state.state }}"
      old_state: "{{ trigger.from_state.state }}"
      
      # Находим конфигурацию для текущей сущности
      entity_config: >
        {% set config = None %}
        {% for item in entities_config %}
          {% if item.entity_id == entity_id %}
            {% set config = item %}
          {% endif %}
        {% endfor %}
        {{ config }}
      
      # Проверяем критическое состояние
      check_result: >
        {% set c = entity_config %}
        {% if c is none %}
          {{ {'alert': false, 'reason': 'no_config'} }}
        {% else %}
          {% set value = new_state %}
          {% set num_value = value | float(default=none) %}
          {% set is_numeric = num_value is not none %}
          
          {% set alert = false %}
          {% set reason = '' %}
          {% set threshold = 0 %}
          
          {% if is_numeric %}
            {% if c.check_above is defined and num_value > c.check_above %}
              {% set alert = true %}
              {% set reason = 'above' %}
              {% set threshold = c.check_above %}
            {% elif c.check_below is defined and num_value < c.check_below %}
              {% set alert = true %}
              {% set reason = 'below' %}
              {% set threshold = c.check_below %}
            {% endif %}
          {% else %}
            {% if c.check_state is defined and value == c.check_state %}
              {% set alert = true %}
              {% set reason = 'state_match' %}
            {% elif c.check_states is defined and value in c.check_states %}
              {% set alert = true %}
              {% set reason = 'state_in_list' %}
            {% endif %}
          {% endif %}
          
          {{ {'alert': alert, 'reason': reason, 'threshold': threshold, 'is_numeric': is_numeric} }}
        {% endif %}

  - if:
      - condition: template
        value_template: "{{ check_result.alert }}"
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ check_result.reason == 'above' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ telegram_chat_id }}"
                  message: >
                    🚨 *ПРЕВЫШЕНИЕ - {{ entity_config.name | default(entity_id) }}*
                    
                    📊 *Текущее значение:* {{ new_state }}{{ entity_config.unit | default('') }}
                    📈 *Превышен порог:* {{ check_result.threshold }}{{ entity_config.unit | default('') }}
                    ⚠️ *Статус:* Критический
                    
                    💡 *Действие:* {{ entity_config.action | default('Требуется вмешательство') }}
                  parse_mode: markdown
          
          - conditions:
              - condition: template
                value_template: "{{ check_result.reason == 'below' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ telegram_chat_id }}"
                  message: >
                    🚨 *НИЖЕ НОРМЫ - {{ entity_config.name | default(entity_id) }}*
                    
                    📊 *Текущее значение:* {{ new_state }}{{ entity_config.unit | default('') }}
                    📉 *Ниже порога:* {{ check_result.threshold }}{{ entity_config.unit | default('') }}
                    ⚠️ *Статус:* Критический
                    
                    💡 *Действие:* {{ entity_config.action | default('Требуется вмешательство') }}
                  parse_mode: markdown
          
          - conditions:
              - condition: template
                value_template: "{{ check_result.reason in ['state_match', 'state_in_list'] }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ telegram_chat_id }}"
                  message: >
                    🚨 *КРИТИЧЕСКОЕ СОСТОЯНИЕ - {{ entity_config.name | default(entity_id) }}*
                    
                    📊 *Текущее состояние:* {{ new_state }}
                    ⚠️ *Статус:* Требует внимания
                    
                    💡 *Действие:* {{ entity_config.action | default('Требуется проверка') }}
                  parse_mode: markdown

mode: single