blueprint:
  name: Universal Critical Values Monitor (hold per entity)
  description: 'Мониторинг критических значений с удержанием для каждого сенсора. Уведомления приходят только если значение остаётся критическим hold_seconds.'
  domain: automation
  input:
    entities_config:
      name: Entities Configuration
      description: |
        Пример:
        - entity_id: sensor.temp
          name: Температура
          unit: "°C"
          check_above: 28
          check_below: 18
          hold_seconds: 60
          action: Включить кондиционер
      selector:
        object:
          multiple: true
    delay_seconds:
      name: Delay before initial check (sec)
      description: Короткая пауза после триггера, чтобы отфильтровать быстрые колебания
      default: 5
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: sec
          step: 1.0
          mode: slider

trigger:
  - platform: state
    entity_id: >
      {% set entities = [] %}
      {% for item in inputs.entities_config %}
        {% set _ = entities.append(item.entity_id) %}
      {% endfor %}
      {{ entities }}

variables:
  entities_config: !input 'entities_config'
  delay_seconds: !input 'delay_seconds'
  entity_id: "{{ trigger.entity_id }}"
  state_now: "{{ states(trigger.entity_id) }}"

action:
  - delay:
      seconds: "{{ delay_seconds }}"
  
  - variables:
      entity_config: >
        {% for item in entities_config %}
          {% if item.entity_id == entity_id %}
            {{ item }}
          {% endif %}
        {% endfor %}
      hold_seconds: "{{ entity_config.hold_seconds | default(30) }}"
      check_result: >
        {% if entity_config is not defined or entity_config is none %}
          {{ {'alert': false} }}
        {% else %}
          {% set value = state_now %}
          {% set num_value = value | float(default=none) %}
          {% set is_numeric = num_value is not none %}
          
          {% set alert = false %}
          {% set reason = '' %}
          {% set threshold = 0 %}
          
          {% if is_numeric %}
            {% if entity_config.check_above is defined and num_value > entity_config.check_above %}
              {% set alert = true %}
              {% set reason = 'above' %}
              {% set threshold = entity_config.check_above %}
            {% elif entity_config.check_below is defined and num_value < entity_config.check_below %}
              {% set alert = true %}
              {% set reason = 'below' %}
              {% set threshold = entity_config.check_below %}
            {% endif %}
          {% else %}
            {% if entity_config.check_state is defined and value == entity_config.check_state %}
              {% set alert = true %}
              {% set reason = 'state_match' %}
            {% elif entity_config.check_states is defined and value in entity_config.check_states %}
              {% set alert = true %}
              {% set reason = 'state_in_list' %}
            {% endif %}
          {% endif %}
          
          {{ {'alert': alert, 'reason': reason, 'threshold': threshold} }}
        {% endif %}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ check_result.alert }}"
        sequence:
          - delay:
              seconds: "{{ hold_seconds }}"
          
          - variables:
              state_now: "{{ states(entity_id) }}"
              check_result_after: >
                {% set value = state_now %}
                {% set num_value = value | float(default=none) %}
                {% set is_numeric = num_value is not none %}
                
                {% set alert = false %}
                {% set reason = '' %}
                {% set threshold = 0 %}
                
                {% if is_numeric %}
                  {% if entity_config.check_above is defined and num_value > entity_config.check_above %}
                    {% set alert = true %}
                    {% set reason = 'above' %}
                    {% set threshold = entity_config.check_above %}
                  {% elif entity_config.check_below is defined and num_value < entity_config.check_below %}
                    {% set alert = true %}
                    {% set reason = 'below' %}
                    {% set threshold = entity_config.check_below %}
                  {% endif %}
                {% else %}
                  {% if entity_config.check_state is defined and value == entity_config.check_state %}
                    {% set alert = true %}
                    {% set reason = 'state_match' %}
                  {% elif entity_config.check_states is defined and value in entity_config.check_states %}
                    {% set alert = true %}
                    {% set reason = 'state_in_list' %}
                  {% endif %}
                {% endif %}
                
                {{ {'alert': alert, 'reason': reason, 'threshold': threshold} }}
          
          - condition: template
            value_template: "{{ check_result_after.alert }}"
          
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason == 'above' }}"
                sequence:
                  - service: notify.send_message
                    data:
                      message: >
                        🚡 *ПРЕВЫШЕНИЕ - {{ entity_config.name | default(entity_id) }}*
                        
                        📊 Текущее: {{ state_now }}{{ entity_config.unit | default('') }}
                        📈 Порог: {{ check_result_after.threshold }}{{ entity_config.unit | default('') }}
                        ⚠️ Статус: Критический
                        
                        💡 {{ entity_config.action | default('Требуется вмешательство') }}
              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason == 'below' }}"
                sequence:
                  - service: notify.send_message
                    data:
                      message: >
                        🚡 *НИЖЕ НОРМЫ - {{ entity_config.name | default(entity_id) }}*
                        
                        📊 Текущее: {{ state_now }}{{ entity_config.unit | default('') }}
                        📉 Порог: {{ check_result_after.threshold }}{{ entity_config.unit | default('') }}
                        ⚠️ Статус: Критический
                        
                        💡 {{ entity_config.action | default('Требуется вмешательство') }}
              - conditions:
                  - condition: template
                    value_template: "{{ check_result_after.reason in ['state_match', 'state_in_list'] }}"
                sequence:
                  - service: notify.send_message
                    data:
                      message: >
                        🚡 *КРИТИЧЕСКОЕ СОСТОЯНИЕ - {{ entity_config.name | default(entity_id) }}*
                        
                        📊 Состояние: {{ state_now }}
                        ⚠️ Статус: Требует внимания
                        
                        💡 {{ entity_config.action | default('Требуется проверка') }}

mode: single
