blueprint:
  name: Critical Value Monitor (single entity)
  description: >
    Мониторинг критических значений с удержанием для одной сущности. 
    Уведомления приходят только если значение остаётся критическим hold_seconds.
  domain: automation
  input:
    entity:
      name: Entity to monitor
      description: Сенсор или бинарный сенсор, который нужно мониторить
      selector:
        entity:
    name:
      name: Display Name
      description: Человекочитаемое имя для уведомлений
      default: ""
    unit:
      name: Unit
      description: Единица измерения для сенсора
      default: ""
    check_above:
      name: Check Above
      description: Порог, при превышении которого срабатывает alert
      default: null
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
    check_below:
      name: Check Below
      description: Порог, при падении ниже которого срабатывает alert
      default: null
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
    check_state:
      name: Check State
      description: Если сенсор — нечисловой, сработает alert при совпадении
      default: ""
    check_states:
      name: Check States
      description: Список допустимых критических значений (нечисловой сенсор)
      default: []
      selector:
        object:
          multiple: true
    hold_seconds:
      name: Hold Seconds
      description: Время удержания состояния перед уведомлением
      default: 60
      selector:
        number:
          min: 0
          max: 3600
          step: 1
    delay_seconds:
      name: Delay before initial check
      description: Пауза после изменения состояния для фильтрации быстрых колебаний
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1

trigger:
  - platform: state
    entity_id: !input entity

variables:
  state_now: "{{ states(trigger.entity_id) }}"
  entity_name: "{{ input_name | default(states(trigger.entity_id).name) }}"
  unit: "{{ unit | default('') }}"
  hold_seconds: !input hold_seconds
  delay_seconds: !input delay_seconds

action:
  - delay:
      seconds: "{{ delay_seconds }}"

  - variables:
      num_value: "{{ state_now | float(default=None) }}"
      is_numeric: "{{ num_value is not none }}"
      alert: false
      reason: ""
      threshold: 0

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% if is_numeric %}
                {% if check_above is not none and num_value > check_above %}
                  true
                {% elif check_below is not none and num_value < check_below %}
                  true
                {% else %}
                  false
                {% endif %}
              {% else %}
                {% if check_state != "" and state_now == check_state %}
                  true
                {% elif check_states | length > 0 and state_now in check_states %}
                  true
                {% else %}
                  false
                {% endif %}
              {% endif %}
        sequence:
          - delay:
              seconds: "{{ hold_seconds }}"
          
          - variables:
              state_after: "{{ states(trigger.entity_id) }}"
              num_after: "{{ state_after | float(default=None) }}"
              is_numeric_after: "{{ num_after is not none }}"
              alert_after: false
              reason_after: ""
              threshold_after: 0

          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {% if is_numeric_after %}
                        {% if check_above is not none and num_after > check_above %}
                          true
                        {% elif check_below is not none and num_after < check_below %}
                          true
                        {% else %}
                          false
                        {% endif %}
                      {% else %}
                        {% if check_state != "" and state_after == check_state %}
                          true
                        {% elif check_states | length > 0 and state_after in check_states %}
                          true
                        {% else %}
                          false
                        {% endif %}
                      {% endif %}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ is_numeric_after and check_above is not none and num_after > check_above }}"
                        sequence:
                          - service: notify.send_message
                            data:
                              message: >
                                🚡 *ПРЕВЫШЕНИЕ - {{ entity_name }}*
                                📊 Текущее: {{ state_after }}{{ unit }}
                                📈 Порог: {{ check_above }}{{ unit }}
                                ⚠️ Статус: Критический
                      - conditions:
                          - condition: template
                            value_template: "{{ is_numeric_after and check_below is not none and num_after < check_below }}"
                        sequence:
                          - service: notify.send_message
                            data:
                              message: >
                                🚡 *НИЖЕ НОРМЫ - {{ entity_name }}*
                                📊 Текущее: {{ state_after }}{{ unit }}
                                📉 Порог: {{ check_below }}{{ unit }}
                                ⚠️ Статус: Критический
                      - conditions:
                          - condition: template
                            value_template: "{{ not is_numeric_after and (state_after == check_state or state_after in check_states) }}"
                        sequence:
                          - service: notify.send_message
                            data:
                              message: >
                                🚡 *КРИТИЧЕСКОЕ СОСТОЯНИЕ - {{ entity_name }}*
                                📊 Состояние: {{ state_after }}
                                ⚠️ Статус: Требует внимания

mode: single
